services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./BaseCRMDapper.sql:/tmp/BaseCRMDapper.sql
      - ./BaseCRMDapperContrib.sql:/tmp/BaseCRMDapperContrib.sql
      - ./BaseCRMEF.sql:/tmp/BaseCRMEF.sql
      - ./BaseCRMADO.sql:/tmp/BaseCRMADO.sql
      - ./init-basescrm.sh:/tmp/init-basescrm.sh
    command: /bin/bash ./tmp/init-basescrm.sh